### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by brohammer** [LinkageIO/Minus80#7]
Saw you were adding some cloud functionality. That is something I would use regularly so if you get to a good place and need any help testing lmk!

**Comment by schae234** [comment]
Nice! Yeah, the cloud things will be really helpful for moving frozen datasets around. I am toying around with converting everything to google cloud versus AWS. Do you have any input on that?

**Comment by brohammer** [comment]
Yeah, would be much easier to put everything in a shared bucket and only thaw (unfreeze?) it locally when needed. I am personally only using AWS now but can understand the appeal of GCP as well.
